# Generated by Django 6.0.5 on 2026-05-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_agentresult_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="jd_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
