# Generated by Django 6.0.5 on 2026-05-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_alter_jobapplication_jd_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Applied", "Applied"),
                    ("Interviewed", "Interviewed"),
                    ("Rejected", "Rejected"),
                    ("Offered", "Offered"),
                    ("Processing", "Processing"),
                    ("Failed", "Failed"),
                ],
                default="Processing",
            ),
        ),
    ]
