# Generated by Django 6.0.5 on 2026-05-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_jobapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("interviewed", "Interviewed"),
                    ("rejected", "Rejected"),
                    ("offered", "Offered"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                ],
                default="processing",
            ),
        ),
    ]
